#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'turtle-rainbow','console_scripts','turtle_rainbow'
__requires__ = 'turtle-rainbow'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('turtle-rainbow', 'console_scripts', 'turtle_rainbow')()
    )
